//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajeroAutomatico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajero_CuentaCorriente
    {
        public Nullable<double> saldo { get; set; }
        public long numCuenta { get; set; }
        public string usuario { get; set; }
        public int pin { get; set; }
        public string identificacion { get; set; }
    
        public virtual Cajero_CuentasClientes Cajero_CuentasClientes { get; set; }
    }
}
