//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajeroAutomatico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajero_CuentasClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cajero_CuentasClientes()
        {
            this.Cajero_CuentaCorriente = new HashSet<Cajero_CuentaCorriente>();
        }
    
        public string Usuario { get; set; }
        public string Identificacion { get; set; }
        public int Pin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cajero_CuentaCorriente> Cajero_CuentaCorriente { get; set; }
    }
}
